# Generated by Django 4.1.7 on 2023-03-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0006_produitnc_alter_categorie_name_commande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='produits',
            new_name='Produit',
        ),
    ]
